services:
  - type: web
    name: NA-Corp-Backend
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install cmake==3.27.7 wheel setuptools
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0